services:
  frankenphp:
    image: dunglas/frankenphp:php8.3.10@sha256:f0fb772c69ee4a53aff74731e3142a9c9bb6ca6492c5b41f159553755055cc28
    container_name: linktank-frankenphp
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    depends_on:
      - app
    volumes:
      - ./app:/app
      - ./frankenphp-data:/data
      - ./frankenphp-config:/config
# Uncomment below if needing to disable auto-https from inside this container
#    environment:
#      SERVER_NAME: :80
    networks:
      - app

  app:
    build:
     context: .
     dockerfile: Dockerfile
    container_name: linktank-app
    working_dir: /var/www
    user: "1000:1000"
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./app:/var/www
    networks:
      - app

networks:
  app:
    driver: bridge
